from __future__ import annotations

from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]
PACKAGE_ROOT = REPO_ROOT / "pebench"
DEFAULT_PE_GPT_ROOT = REPO_ROOT / ("PE" + "-GPT")
DEFAULT_FLYBACK_TASK_DIR = PACKAGE_ROOT / "tasks" / "flyback"
DEFAULT_TASK_DIR = DEFAULT_FLYBACK_TASK_DIR
DEFAULT_LEGACY_TASK_DIR = PACKAGE_ROOT / "tasks" / "library"
DEFAULT_TOPOLOGY_FULL_TASK_DIR = PACKAGE_ROOT / "tasks" / "topology_full"
DEFAULT_TOPOLOGY_SCOUT_TASK_DIR = DEFAULT_TOPOLOGY_FULL_TASK_DIR
DEFAULT_INVERTER_TASK_DIR = PACKAGE_ROOT / "tasks" / "inverter"
DEFAULT_CATALOG_PATH = REPO_ROOT / "assets" / "catalogs" / "components.yaml"
DEFAULT_SCOUT_CATALOG_PATH = REPO_ROOT / "assets" / "catalogs" / "topology_components.yaml"
DEFAULT_INVERTER_CATALOG_PATH = REPO_ROOT / "assets" / "catalogs" / "inverter_components.yaml"
DEFAULT_RESULTS_ROOT = REPO_ROOT / "results"
DEFAULT_PEBENCH_RESULTS_ROOT = DEFAULT_RESULTS_ROOT / "pebench"
DEFAULT_ARCHIVE_RESULTS_ROOT = DEFAULT_RESULTS_ROOT / "archive"
DEFAULT_AUDITS_RESULTS_ROOT = DEFAULT_RESULTS_ROOT / "audits"
DEFAULT_CANONICAL_RESULTS_ROOT = DEFAULT_RESULTS_ROOT / "canonical"
DEFAULT_ABLATIONS_RESULTS_ROOT = DEFAULT_RESULTS_ROOT / "ablations"
DEFAULT_REPEATABILITY_RESULTS_ROOT = DEFAULT_RESULTS_ROOT / "repeatability"
DEFAULT_PROVENANCE_ROOT = REPO_ROOT / "sources" / "provenance"
